# Generated by Django 4.1 on 2024-03-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="textDic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("message_content", models.TextField()),
                ("author_name", models.CharField(max_length=50)),
            ],
        ),
    ]
